config/routes.rb
Bill::Application.routes.draw do

  resources :groups do
    resources :users
	end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
    get 'users' => :users
    get 'index' => :index
  end

  resources :event_types

  resources :people, :places, :events

  root :to => "sessions#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :event_type_id, :presence => true
  validates :group_id, :presence => true
  validates :place_id, :presence => true

	has_many :event_users
	has_many :users, :through => :event_users

	belongs_to :place
	belongs_to :group
	belongs_to :event_type
end

app/models/event_type.rb
class EventType < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
  
	has_many :events
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
#	before_filter :find_group
#	before_filter :find_event, :only => ['show', 'detail', 'add', 'detail2', 'add2', 'update', 'edit', 'destroy']
  # GET /events
  # GET /events.json
  def index
    @events = @group.events

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    ##
    @event = Event.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json  { respond_event @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new
    groups = @user.groups
    groups_users = {}    
    groups.each do |group|
      groups_users[group.id] = group.users
    end
    respond_to do |format|
      format.html # new.html.erb
      format.json do
        respond_succ :groups => groups, :event_types => EventType.all, :places => Place.all, :groups_users => groups_users
      end
    end
  end

  # GET /events/1/edit
  def edit
    
  end

#  group_id, date, event_type_id, place_id, user_ids=xx,xx,
  # POST /events
  # POST /events.json
  def create
    @event = Event.new(:event_type_id => params[:event_type_id], :place_id => params[:place_id], :group_id => params[:group_id], :date => params[:date])
    member = Membership.find_by_user_id_and_group_id(@user.id, @event.group_id)
    if !member
      respond_fail
      return
    end
    group = Group.find(@event.group_id)
    users = group.users
    user_map = {}
    users.map { |u| user_map[u.id] = u  }
    ## calc users pay & consume    
    user_ids = params[:user_ids]
    if user_ids == nil || user_ids.strip.length == 0
      respond_fail
      return
    end
    ids = user_ids.split(',')
    validate_ids = ids.select {|id| (/[0-9]+/ =~ id) && id.to_i != @user_id && user_map[id.to_i] }
    validate_ids.uniq!

    pay = params[:pay]
    if pay.nil? || pay.to_f < 0.1
      respond_fail
      return
    end
    total_pay = pay.to_f
    average = (total_pay /  (validate_ids.length + 1))
    
    evts = []
    validate_ids.each do |id|
      evt = EventUser.new(:user_id => id, :consume => average, :pay => 0)
      evts << evt
    end
    
    evt = EventUser.new(:user_id => @user_id, :consume => average, :pay => total_pay)
    evts << evt
    @event.event_users = evts

    respond_to do |format|
      if @event.save
        format.html { redirect_to( event_path(@event), :notice => 'Event was successfully created.') }
        format.json  { respond_event_summary @event}
      else
        format.html { render :action => "new" }
        format.json  { respond_fail }
      end
    end
  end

  def detail 
  end

  def add
    if (params[:event][:person_ids] && @event.update_attributes(params[:event]))
	redirect_to detail2_group_event_path(@group, @event)
    else
	redirect_to detail_group_event_path(@group, @event)
    end
  end

  def detail2
  end

  def add2
    # sum pay
    people = params[:event_person]
    db = []
    sum = 0
    for id, person in people do
      pay = person[:pay].to_i 
      consume = person[:consume].to_i
      sum += pay
      db.push([id, pay, consume])
    end

    equal = sum / people.size
    db.each do |ep|
      EventPerson.find(ep[0]).update_attributes(:pay => ep[1], :consume => equal)
    end 
    redirect_to group_event_path(@group, @event), :notice => sum
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to detail_group_event_path(@group, @event), :notice => 'Event was successfully updated.' }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(group_events_path(@group)) }
      format.json  { head :ok }
    end
  end

  private

  def find_event 
    @event = @group.events.find(params[:id])
  end

  def respond_event(event)
    respond_succ event_summary(event)
  end

  def event_summary(event)
    {:group => event.group, :date => event.date, :event_type => event.event_type, :place => event.place, :users => event.users}
  end

  def respond_event_summary(event)
    account = Group.find(event.group_id).summary(@user_id)
    res = {:account => account, :summary => event_summary(event)}
    respond_succ res
  end
  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_detail.html.erb
<%= form_tag add_group_event_path(@group, @event) do |f|%>
	<%= flash[:notice]%>
  <div class="field">
  <%= label_tag	'People' %><br />
	  <table>
		  <tr>
			  <th>Name</th>
		  </tr>
	  <% @group.people.each do |person|%>
   		<tr>
			<td>
			  <%= check_box_tag "event[person_ids][]", person.id, @event.people.include?(person) %>
			  <%= label_tag person.name %>	
			</td>
		</tr> 
	  <% end %>
  </table>
  <%= submit_tag 'OK'%>
  </div>
<% end %>

app/views/events/_detail2.html.erb
<%= form_tag add2_group_event_path(@group, @event) do |f|%>
	<%= flash[:notice]%>
  <div class="field">
  <%= label_tag	'People' %><br />
	  <table>
		  <tr>
			  <th>Name</th>
			  <th>Pay</th>
			  <th>Consume</th>
		  </tr>
	  <% @event.event_people.each do |person|%>
	    <%= fields_for person, :index => person.id do |person_form|%>
   		<tr>
			<td><%= Person.find(person.person_id).name %><%= person_form.hidden_field :id %></td>
			<td><%= person_form.text_field :pay, :size => 6 %></td>
			<td><%= person_form.text_field :consume, :size => 6%></td>
		</tr> 
	    <% end %>
	  <% end %>
  </table>
  <%= submit_tag 'OK'%>
  </div>
<% end %>

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= flash[:notice]%>
  <div class="field">
	  <%= f.label :group_id %><br />
	  <%= select_tag(:group_id, options_from_collection_for_select(@user.groups, :id, :name, @event.group_id))%>
  </div>
  <div class="field">
	  <%= f.label :place_id %><br />
	  <%= select_tag(:place_id, options_from_collection_for_select(Place.all, :id, :name, @event.place_id))%>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= text_field_tag :date %>
  </div>
  <div class="field">
    <%= f.label :event_type_id %><br />
    <%= select_tag(:event_type_id, options_from_collection_for_select(EventType.all, :id, :name, @event.event_type_id)) %>
  </div>
  <div class="field">
    <%= label_tag :pay %><br />
    <%= text_field_tag :pay %>
  </div>
  <div class="field">
    <%= label_tag :user_ids %><br />
    <%= text_field_tag :user_ids %>
  </div>

  <div class="actions">
    <%= submit_tag %>
  </div>
<% end %>

app/views/events/detail.html.erb
<h1>Bill detail for event</h1>

<%= render 'detail' %>

<%= link_to 'Back', group_events_path(@group) %>

app/views/events/detail2.html.erb
<h1>Bill detail for event</h1>

<%= render 'detail2' %>

<%= link_to 'Back', group_events_path(@group) %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', group_event_path(@group, @event) %> |
<%= link_to 'Back', group_events_path(@group) %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Place</th>
    <th>Date</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.place.name %></td>
    <td><%= event.date.to_date %></td>
    <td><%= event.event_type.name %></td>
    <td><%= link_to 'Detail', group_event_path(@group, event) %></td>
    <td><%= link_to 'Edit', edit_group_event_path(@group, event) %></td>
    <td><%= link_to 'Delete', group_event_path(@group, event), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_group_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Place:</b>
  <%= @event.place.name %>
</p>

<p>
  <b>Date:</b>
  <%= @event.date %>
</p>

<p>
  <b>Type:</b>
  <%= @event.event_type.name %>
</p>

<table>
	<tr>
		<th>Name</th>
		<th>Pay</th>
		<th>Consume</th>
	</tr>
	<% @event.event_users.each do |p| %>
	<tr>
		<td><%= p.user.name %></td>
		<td><%= p.pay %></td>
		<td><%= p.consume%></td>
	</tr>
	<% end %>
</table>

<%= link_to 'Edit', edit_events_path(@event) %> |
<%= link_to 'To Events', events_path %>